# Generated by Django 5.0.1 on 2025-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('owner_id', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pimg', models.ImageField(upload_to='media/')),
                ('price', models.BigIntegerField(default=0)),
                ('wattage', models.CharField(blank=True, max_length=50)),
                ('voltage', models.CharField(blank=True, max_length=50)),
                ('warrenty', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description1', models.TextField(default='No description provided.')),
                ('solar_panel', models.BooleanField(default=False)),
                ('solar_heater', models.BooleanField(default=False)),
                ('inverter', models.BooleanField(default=False)),
                ('solar_cooker', models.BooleanField(default=False)),
                ('luminous', models.BooleanField(default=False)),
                ('loom', models.BooleanField(default=False)),
                ('hi_mo', models.BooleanField(default=False)),
                ('discount_10', models.BooleanField(default=False)),
                ('discount_20', models.BooleanField(default=False)),
                ('discount_30', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(default='No description provided.')),
                ('cart', models.IntegerField(default=0)),
                ('buy', models.IntegerField(default=0)),
                ('arrival_time', models.DateField(default=None, null=True)),
                ('status', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField(default='9090909090', max_length=10)),
                ('city', models.CharField(default='', max_length=15)),
                ('description1', models.TextField(default='No description provided.')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_10', models.BooleanField(default=False)),
                ('discount_20', models.BooleanField(default=False)),
                ('discount_30', models.BooleanField(default=False)),
                ('gstin', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_time', models.CharField(null=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField(default='9090909090', max_length=10)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
