# Generated by Django 5.0.1 on 2025-05-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='arrival_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
